### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by bamnet** [concerto/concerto-player#9]
Can we support the Raspberry Pi as a proper Concerto 2 Player?  I can conjure a few up for testing if needed.

**Comment by augustf** [comment]
@mfrederickson Has concerto-player (not just bandshelld) been working on the pi for you?

**Comment by mfrederickson** [comment]
We are not yet using the Pi, and now ours is outdated.  We were going to but never quite got there.

**Comment by kench** [comment]
Adding a mental note here: http://blog.kmp.or.at/2012/05/build-your-own-raspberry-pi-image/
Documentation for building Raspbian images on the Internet is very disorganized and could be out of date, but if it's a use-case that's strongly desired (it seems so from the mailing lists).

Personally, I recommend the Amazon* Fire TV Stick ([Amazon.com](http://amazon.com/dp/B00GDQ0RMG)) ([UK](http://amazon.co.uk/dp/B00KAKUN3E)) ([DE](amazon.de/dp/B00KQEIMY6)) at that price point and the Concerto Player app from the Amazon Appstore.  From my own testing, it seems to work well.

*Disclosure:* I could be biased since I work there.
